name: grocery2
description:
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  # HTTP and API
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0

  # Navigation
  go_router: ^17.2.1

  # Utilities
  equatable: ^2.0.8
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  # Phone Number
  flutter_intl_phone_field: ^0.0.7
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.5
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  
  gap: ^3.0.1
  flutter_secure_storage: ^10.0.0
  google_fonts: ^6.2.1
  skeletonizer: ^2.1.3
  carousel_slider: ^5.1.2
  #for otp input
  pinput: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
